name: CI

on:
  push:
    branches:
      - "**"
    tags:
      - "v*"
  pull_request:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build & Verify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Make Gradle Wrapper executable
        run: chmod +x gradlew

      - name: Verify & Build
        run: ./gradlew spotlessCheck check build --no-daemon

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: Terracotta
          path: |
            modules/terracotta-core/build/libs/*.jar
            modules/terracotta-gradle-plugin/build/libs/*.jar
            modules/terracotta-provider-modrinth/build/libs/*.jar
            modules/terracotta-provider-hangar/build/libs/*.jar
            modules/terracotta-state-filesystem/build/libs/*.jar
          if-no-files-found: error
          retention-days: 30
